NAME= hipHopArrays
SRC= main.cpp
FLAGS= -Wextra -Werror -Wall -std=c++98

all: $(NAME)

$(NAME):
	@g++ $(FLAGS) $(SRC) -o $(NAME)
	@echo ...This excercise is a tribute to Naughty By Nature and their 1993 track Hip Hop Hooray
	@echo ...while implementing an array class template...

fclean:
	@rm -f $(NAME)
	@echo ...don't mind me i'm just cleaning up...

re: fclean all
