NAME= EasyFind
SRC= main.cpp
FLAGS= -Wextra -Werror -Wall -std=c++98 -std=c++11

all: $(NAME)

$(NAME):
	@g++ $(FLAGS) $(SRC) -o $(NAME)
	@echo ...hate to sound sleazy but tease me, i dont want it if its that easy..to find
	

fclean:
	@rm -f $(NAME)
	@echo ...don't mind me i'm just cleaning up...

re: fclean all
