NAME= MutantStax
SRC= main.cpp 
FLAGS= -Wextra -Werror -Wall -std=c++98 -std=c++11

all: $(NAME)

$(NAME):
	@g++ $(FLAGS) $(SRC) -o $(NAME)
	@echo ...The Final C++ Exercise...
fclean:
	@rm -f $(NAME)
	@echo ...don't mind me i'm just cleaning up...

re: fclean all
