NAME= bCratz
SRC= Bureucrat.cpp main.cpp
FLAGS= -Wextra -Werror -Wall -std=c++98

all: $(NAME)

$(NAME):
	@g++ $(FLAGS) $(SRC) -o $(NAME)
	@echo ...About to get bored by Bureucracy...

fclean:
	@rm -f $(NAME)
	@echo ...Mush on the pavement, time to clean up...

re: fclean all
